name: Play CI
on:
  push:
    branches:
      - '**'
      - '!refs/tags/.*'
    tags-ignore:
      - '**'
    paths-ignore:
      - 'docs/**'
      - mkdocs.yml
      - '*.md'
      - .github/workflows/website_preview.yml
      - .github/workflows/website_deploy.yml
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - 'docs/**'
      - mkdocs.yml
      - '*.md'
      - .github/workflows/website_preview.yml
      - .github/workflows/website_deploy.yml

jobs:
  build:
    name: Build
    if: "github.event == 'push' || github.repository != github.event.pull_request.head.repo.full_name"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        java_version: [19]

    steps:
      - name: Environment
        run: env | sort

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true

      - name: Setup Java ${{ matrix.java_version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{matrix.java_version}}
          distribution: 'temurin'
          architecture: x64
          cache: gradle

      - name: Compile
        run: make compile
        env:
          GRADLE_OPTS: '-Dorg.gradle.daemon=false'

      - name: Tests
        if: "!contains(github.event.head_commit.message, '[skip test]')"
        run: |
          make check

      - name: Publish tests report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-jdk-${{ matrix.java_version }}
          path: |
            **/build/reports/tests/test

      - name : Add coverage to PR
        id : jacoco
        uses : madrapps/jacoco-report@v1.7.1
        with :
          paths : |
            **/build/reports/jacoco/test/jacocoTestReport.xml
          token : ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall : 60
          min-coverage-changed-files : 60
          title : Code Coverage Report
          pass-emoji : ':green_circle:'
          fail-emoji : ':red_circle:'

      - name : Get the Coverage info
        run : |
          echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
          echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"